apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: localhost:8083/my-python-app:build-1 # <-- Jenkins buraya müdahale edecek
        ports:
        - containerPort: 5000
