apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        # İmaj yolunu Jenkinsfile'daki NEXUS_REPO yapısına uygun hale getirdik
        image: host.minikube.internal:8083/my-python-app:latest 
        ports:
        - containerPort: 5000
