pipeline {
    agent any

    environment {
        // VPC'deki sonar'da my-python-app şeklinde proje adı verildiği ve aşağıda direkt adı ile
		// tanımlandığı için, buradaki definition yorum satırına çekilmiştir. APP_NAME = 'python-flask-app'
        DOCKER_IMAGE = 'my-python-app:latest'
        // Dosyalarının bulunduğu alt klasör yolu, evdeki WSL Ubuntu makinesi için aşağıdaki şekilde(day-08 ile başlayan)
		// AWS VPC ortamında kullanım durumuna göre birbiri yerine aktif edilip yorum satırına alınmalı(VPC için day-09)
        // WORK_DIR = 'day-08/git-stored-version' 
		WORK_DIR = 'day-09/'
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Kod GitHub deposundan çekildi."
                sh 'ls -la'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    dir("${WORK_DIR}") {
						withCredentials([string(credentialsId: 'sonar-token', variable: 'MY_SONAR_TOKEN')]) {
                    		echo 'SonarQube Statik Kod Analizi Başlatılıyor...'
                    		sh 'chmod -R 777 .'
                    		sh 'docker run --rm --net cicd-net -e SONAR_TOKEN=' + MY_SONAR_TOKEN + ' --volumes-from jenkins -w "' + WORKSPACE + '/day-09" sonarsource/sonar-scanner-cli -Dsonar.host.url=http://sonarqube:9000 -Dsonar.projectKey=my-python-app -Dsonar.sources=.'
                            
                            // DİKKAT:
                            // 1. -v yerine "--volumes-from jenkins" kullanıyoruz. Böylece Jenkins'in volume alanı aynen aktarılıyor.
                            // 2. -w ile Scanner'ın doğrudan doğru workspace alt klasöründe çalışmasını sağlıyoruz.

                        }
                    }
                }
            }
        }
        
        stage('Build Docker Image') {
            steps {
                // Docker build komutunu da ilgili klasörün içinde çalıştırıyoruz
                dir("${WORK_DIR}") {
                    echo 'Docker İmajı Build Ediliyor...'
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }
		
		stage('Push Docker Image to Nexus') {
            steps {
                echo 'Docker İmajı Nexus Repository Manager adresine yükleniyor...'
                script {
                    withCredentials([usernamePassword(credentialsId: 'nexus-docker-creds', usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                        sh """
                            echo "Nexus'a login olunuyor..."
                            docker login -u \${NEXUS_USER} -p \${NEXUS_PASS} localhost:8083

							echo "İmaj Nexus formatında etiketleniyor..."
                            docker tag ${DOCKER_IMAGE} localhost:8083/${DOCKER_IMAGE}
                            
                            echo "İmaj Nexus'a pushlanıyor..."
                            docker push localhost:8083/my-python-app:latest
                        """
                    }
                }
            }
        }		
		
        stage('Test & Verify') {
            steps {
                echo 'Uygulama İmajı Doğrulanıyor...'
                sh 'docker images | grep my-python-app'
            }
        }
    }

	   

    post {
        always {
            echo 'Pipeline tamamlandı.'
        }
        success {
            echo 'Tebrikler! Kod GitHub depodan alındı, analiz edildi ve build başarılı.'
        }
        failure {
            echo 'Hata! Pipeline bir adımda başarısız oldu.'
        }
    }
}
