apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: web  # Hangi Pod'lara gideceğini buradan anlıyor
  ports:
    - port: 80         # Servisin kendi iç portu
      targetPort: 80   # Pod'un (Nginx'in) portu
      nodePort: 30080  # Dışarıya açacağımız port (Terraform'da izin vermiştik)
